Initialize project with components
gabyse1/bookstore pull request #1
Opened 2022-02-22 22:43 UTC by gabyse1

## Changes to the project
- Create the files *books.js, categories.js, and configureStore.js* files to set *redux actions and reducers*.
- Create and set *Navbar component*.
- Create and set *Footer component*.
- Create ans set *Categories component*.
- Create and set *BookList component*.
- Create and set *BookItem component*.
- Create and set *BookInput component*.
- Create and set *Books component* using *BookList, BookItem, and BookInput components*.
- Set all components inside of *App component* creating the *navigator routes*.
- Create basic scss files to set *typography, color, and mixin* reusable classes.
- Set general styles in *base.scss* file.
- Set Navbar component styles in *navbar.scss* file.
- Set Footer component styles in *footer.scss* file.
- Set Books component styles in *books.scss* file
- Create *App.scss* file to join styles from all components.
- Update *README.md* file.

2022-02-22 23:40 UTC, mmsesay requested changes
Hi @gabyse1, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-22 23:40 UTC, mmsesay commented on src/components/BookList.js
> +    <BookItem />
- [ ] From the suggestion above, you can just make a static array of books for now since your redux is not set up yet. Loop through the data and pass it in as props to the `Books`. In that case, instead of having 3 calls of the `BookItem` component, you will just have one. I.e `Books` 

See example:
```
const booksArray = [
   // book objects goes here
];

const BookList = () => {
   <>
    {booksArray && booksArray.map((data, index) => <Books key={index} book={data} />)}
    <BookInput />
  </>
};

2022-02-22 23:40 UTC, mmsesay commented on src/components/BookInput.js
> +  </form>
- [ ] Please add an input field for an author.

2022-02-22 23:40 UTC, mmsesay commented on src/components/App.js
> +        <Route path="/" element={<Books />} />
- [ ] Please set the `BookList` as the default for your `/` home path. It should be responsible to render the `Book` component and the component for creating a new book.

2022-02-22 23:40 UTC, mmsesay commented on src/components/Books.js
> +  </main>
- [ ] The book component should not have all these codes and must not be the default page. It will be nice to make it take a prop and render the title and author name. By doing so you might not need all the extra codes and any other component that is making use of the `Books` will just pass the data in.

See example:
```
const Books = (prop) => {
    const {  title, author } = prop.book;
    
    return (
      <div>
         // your title and author goes in here with their own HTML tags.
      </div>
   );
};
```

Note: I think if you implement this change, you might not need the  `BookItem` component. Because the `Books` is already handling its functionalities right?

2022-02-23 01:29 UTC, gabyse1 commented on src/components/Books.js
> +  </main>
## Hello @mmsesay 👋 
Thank you for your suggestions.
I have worked on them. 👍

2022-02-23 01:43 UTC, rloterh approved these changes
## Status: Approved :heavy_check_mark:

Hi Gaby, 

Your project is complete! Great job for making the necessary changes recommended in the previous review. There is nothing else to say other than... it's time to merge it 🍾 :shipit:. Congratulations! 🎉🥂

<br>
Cheers and Happy coding!👏 💻 🍷 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 1 more limited review per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-23 11:07 UTC, merged

2022-02-23 14:07 UTC, gabyse1 commented
> ## Status: Approved ✔️
> Hi Gaby,
> 
> Your project is complete! Great job for making the necessary changes recommended in the previous review. There is nothing else to say other than... it's time to merge it 🍾 :shipit:. Congratulations! 🎉🥂
> 
> 
> Cheers and Happy coding!👏 💻 🍷
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 1 more limited review per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

# Hello @rloterh 👋 
First of all, thank you for your time to review my project.
I have some issues to submit my project. The *submit* button change to *Changes Required*. Thats the reason I can not submit my project.
I would like to ask you kindly, maybe you know how can I solve it?
###Thank you very much in advance. 🙏

2022-02-23 17:05 UTC, bellom commented
@gabyse1 - Sorry for the inconvenience, your dashboard should be fine now 🙂 .